# Use this hook to configure devise mailer, warden hooks and so forth.
# Many of these configuration options can be set straight in your model.
Devise.setup do |config|
  # ...
  # *** We uncommented and updated this line
  config.parent_controller = 'Blast::ApplicationController'
  # ...
  # *** We updated this line
  config.mailer_sender = 'crm@blast.com'

  # ...
  require 'devise/orm/active_record'

  # ...
  # *** We uncommented this line
  config.authentication_keys = [:email]
  # ...
  config.case_insensitive_keys = [:email]
  # ...
  config.strip_whitespace_keys = [:email]
  # ...
  config.skip_session_storage = [:http_auth]
  # ...
  config.stretches = Rails.env.test? ? 1 : 11
  # ...
  config.reconfirmable = true
  # ...
  config.expire_all_remember_me_on_sign_out = true
  # ...
  config.password_length = 6..128
  # ...
  config.email_regexp = /\A[^@\s]+@[^@\s]+\z/
  # ...
  config.reset_password_within = 6.hours
  # ...
  config.sign_out_via = :delete
  # ...
  # *** We uncommented and updated this line
  config.router_name = :blast
  # ...
end
